# .github/workflows/publish.yml
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v0.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use a specific Python version for consistency

    - name: Install uv, build, and twine
      run: |
        python -m pip install --upgrade pip
        pip install uv build twine

    - name: Build package
      run: python -m build --sdist --wheel --outdir dist/ .

    - name: Publish package to PyPI
      # Uses PyPI's trusted publisher feature if configured,
      # otherwise falls back to using the PYPI_API_TOKEN secret.
      # See: https://docs.pypi.org/trusted-publishers/
      uses: pypa/gh-action-pypi-publish@release/v1
      # Optional fallback using API Token (less secure than trusted publishing):
      # with:
      #   password: ${{ secrets.PYPI_API_TOKEN }} 